### ISSUE TITLE
using pico4 cant find controls

### ISSUE THREAD

**Issue by BulbBusinessGaming** [Okabintaro/SubmersedVR#109]
i cant find any control sheet anywhere
and i do not know how to drop items
or open the menu to save and quit
can someone please provide me with the controls for vr
i tried using the controls of a regular controller but the pico4 does not have the three stripes button.. well it does but that just opens the steamvr menu.

**Comment by wulf21** [comment]
Hi, while I don't have pico4 - I have Valve Index - I can tell that the ingame (save/quit) menu can be opened from tablet (the mod a button "open pause menu" under the equipment slots). Also there is a Menu action that can be configured in SteamVR controller configuration (but for me its by default not bound, because there also is the button on the tablet)

I did't figure out how to drop items though as well. Going though the bindings shown in the SteamVR controller config, I would expect the  "Cancel(UI)" action to do that (as "Submit(UI)" is the action that consumes an item), but it does not seem to work (Its bound to right B-button for me)

There doesn't seem to be any default binding for pico4 controllers in code though, so probably SteamVR automatically generated your bindings from the other controllers somehow.

I guess you will need to check your bindings in the controller configuration for the game in SteamVR overlay and either adjust them yourself or check if there is a suitable community binding someone else made and published for your controller.

**Comment by wulf21** [comment]
A note: While trying to adjust my settings I found that unlike with other games my changes in the SteamVR Controller config UI would not actually be saved. It would automatically always reset to default for some reason, so I needed to edit the bindings_knuckles.json containing the mods defaults. But I won't open a separate issue for now since this very well may be something with my SteamVR and not an issue with the mod specifically (though I tried some other games and in them saving worked)

**Comment by BulbBusinessGaming** [comment]
thank you this helped alot and it got the issue fixed! thanks!
