### ISSUE TITLE
Controllers not responding

### ISSUE THREAD

**Issue by SlidingPogba** [Okabintaro/SubmersedVR#115]
Hi, I tried a few times reinstall the game and mods before reporting. 
So, I'm using Pico 4 with Virtual Desktop, and game launching correctly in VR mod, but controllers are not responding. Steam VR overlay working with them correctly tho at the same time. Any hint what should i do to fix it?

UPD: Should mention that i'm talking about below zero

**Comment by wulf21** [comment]
Hi, while I don't have PICO 4 - some general troubleshooting hints:

- make sure you are actually installing the below zero version of the SubmersedVR mod (there is a separate github fork)
- make sure below zero is updated to newest regular version by steam (i.e. automatic updates are on and you did NOT opt into any beta branch)
- make sure BepInEx for Subnautica has been installed correctly and is running (there should open a console window from that when you launch Subnautica and in (path to install location)\Subnautica\BepInEx there should be written a file named LogOutput.log)
- make sure the mod was extracted correctly into the game directory ( in (path to install location)\Subnautica\BepInEx\plugins you should find a file named SubmersedVR.dll if you did it correctly)
- the controller settings for Subnautica in the SteamVR overlay. Make sure the Pico 4 controllers were actually selected and that you have your keys bound (the mod has no default bindings for Pico 4 atm, so I dont know what SteamVR does in this case - i.e. if it translates bindings from a different controller automatically or just leaves it blank. If its left blank, you will have to load community bindings from someone else or make your own keybinds)

If you checked all that and still have trouble, the mod maker will need the mentioned logoutput.txt file in order to find anything that may be wrong with your setup.

**Comment by SlidingPogba** [comment]
- Yes , I double checked verison of mod - SubmersedVR_BZ_0.7.0
- I brought game in Microsoft Store, but after first fail with mod in it I used steam-rip with the lastet version
- BelpInEx Log [LogOutput.log](https://github.com/Okabintaro/SubmersedVR/files/14233432/LogOutput.log)
- dll is there
- Pico 4 controllers in Steam VR displayed as Quest 2 controllers, bindings are correct, works well in other games 

For clear experiment, i'm okay with buiyng another copy of BZ in steam, but prefer to wait for sale, even with my deep love for this game xD

**Comment by Okabintaro** [comment]
The log is too short to see the actualy issue and I would advise you trying with the steam version(there have been a couple of sales until now ;))
The Microsoft Store version of the base game seems incompatible as well so it could be the same issue here.
