### ISSUE TITLE
Beacons not showing 

### ISSUE THREAD

**Issue by VR-2187** [Okabintaro/SubmersedVR#152]
On the original version of the mod, Beacons are completely invisible. and on the bz version they are visable BUT are in the wrong places(the beacon for the landing pod is 10m of were it's suposed to be) This only happens when the mod is active (Aka lauched with a vr headset connected)
I have no idea what could be causing this so please help.

**Comment by Okabintaro** [comment]
There is an experimental feature that puts the Survival Meters on the left wrist like a watch.
Another rather undocumented feature of that is that when you touch that meter with your right hands index finger, it toggles the whole HUD on and off. This is feature I enjoyed to increase immersion when playing, since I found the HUD can be distracting with many beacons and such.

As for the issue with BZ Mod, I am not sure whats the issue there.

**Comment by DeleteRepeat** [comment]
I am also having an issue with my beacons not showing. It was visible at first on the lifepod, but I think after the Aurora blows up, it disappears and the beacons you place also stop showing up. I also have my survival hud on my left arm, but I wasn't having issues with beacons after changing it to my arm. I don't think that was the cause.

**Comment by Okabintaro** [comment]
It most likely that you touched the wrist though, here is the video where I showed it off: https://www.youtube.com/watch?v=fk-d3a3-IVM&t=315s

I am gonna put it behind another toggle because people are getting confused.
